apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: discord-bot
  namespace: discord-bot
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-discord-bot
  target:
    name: discord-bot
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: DISCORD_TOKEN
      remoteRef:
        key: DISCORD_TOKEN
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
