apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: discord-bot
  namespace: discord-bot
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: SecretStore
  target:
    name: discord-bot
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: discord-bot
